### PR TITLE
Added support kernel version newer than  > 5.3

### PR DESCRIPTION
**Pull request by almas**
Added support kernel version newer than  > 5.3

Confirmed on version 6.5.0-28-generic

### CODE REVIEW

**Review by rob-hills — APPROVED** [review]

**Comment by pedroresende** [comment]
Does work using kernel 6.11 on a Macbook pro 13.3

**Comment by pedroresende** [comment]
The one released on Ubuntu 24.10

**Comment by pedroresende** [comment]
With the following error

```
DKMS make.log for applespi-0.1 for kernel 6.11.0-8-generic (x86_64)
Sat Oct 12 09:45:58 PM WEST 2024
make -C /lib/modules/6.11.0-8-generic/build M=/var/lib/dkms/applespi/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.11.0-8-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-14 (Ubuntu 14.2.0-4ubuntu2) 14.2.0
  You are using:           gcc-14 (Ubuntu 14.2.0-4ubuntu2) 14.2.0
  CC [M]  /var/lib/dkms/applespi/0.1/build/apple-ibridge.o
  CC [M]  /var/lib/dkms/applespi/0.1/build/apple-ib-tb.o
  CC [M]  /var/lib/dkms/applespi/0.1/build/apple-ib-als.o
/var/lib/dkms/applespi/0.1/build/apple-ib-tb.c: In function ‘appletb_fill_report_info’:
/var/lib/dkms/applespi/0.1/build/apple-ib-als.c:679:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
  679 |         .remove = appleals_platform_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/applespi/0.1/build/apple-ib-tb.c:949:9: warning: enumeration value ‘HID_REPORT_TYPES’ not handled in switch [-Wswitch]
  949 |         switch (field->report->type) {
      |         ^~~~~~
/var/lib/dkms/applespi/0.1/build/apple-ib-als.c:679:19: note: (near initialization for ‘appleals_platform_driver.<anonymous>.remove’)
/var/lib/dkms/applespi/0.1/build/apple-ib-tb.c: At top level:
/var/lib/dkms/applespi/0.1/build/apple-ib-tb.c:1293:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
 1293 |         .remove = appletb_platform_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/applespi/0.1/build/apple-ib-tb.c:1293:19: note: (near initialization for ‘appletb_platform_driver.<anonymous>.remove’)
/var/lib/dkms/applespi/0.1/build/apple-ibridge.c:192:6: warning: no previous prototype for ‘appleib_detach_and_free_hid_driver’ [-Wmissing-prototypes]
  192 | void appleib_detach_and_free_hid_driver(struct appleib_device *ib_dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/applespi/0.1/build/apple-ib-als.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/applespi/0.1/build/apple-ib-tb.o] Error 1
/var/lib/dkms/applespi/0.1/build/apple-ibridge.c:901:10: error: ‘struct acpi_driver’ has no member named ‘owner’
  901 |         .owner          = THIS_MODULE,
      |          ^~~~~
In file included from ./arch/x86/include/asm/mem_encrypt.h:15,
                 from ./include/linux/mem_encrypt.h:17,
                 from ./arch/x86/include/asm/processor-flags.h:6,
                 from ./arch/x86/include/asm/irqflags.h:5,
                 from ./include/linux/irqflags.h:18,
                 from ./include/linux/spinlock.h:59,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/slab.h:16,
                 from ./include/linux/resource_ext.h:11,
                 from ./include/linux/acpi.h:13,
                 from /var/lib/dkms/applespi/0.1/build/apple-ibridge.c:45:
./include/linux/init.h:180:21: error: initialization of ‘const struct acpi_device_id *’ from incompatible pointer type ‘struct module *’ [-Wincompatible-pointer-types]
  180 | #define THIS_MODULE (&__this_module)
      |                     ^
/var/lib/dkms/applespi/0.1/build/apple-ibridge.c:901:27: note: in expansion of macro ‘THIS_MODULE’
  901 |         .owner          = THIS_MODULE,
      |                           ^~~~~~~~~~~
./include/linux/init.h:180:21: note: (near initialization for ‘appleib_driver.ids’)
  180 | #define THIS_MODULE (&__this_module)
      |                     ^
/var/lib/dkms/applespi/0.1/build/apple-ibridge.c:901:27: note: in expansion of macro ‘THIS_MODULE’
  901 |         .owner          = THIS_MODULE,
      |                           ^~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/applespi/0.1/build/apple-ibridge.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.11.0-8-generic/Makefile:1931: /var/lib/dkms/applespi/0.1/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.11.0-8-generic'
make: *** [Makefile:30: all] Error 2
```
